COMP: Use std::vector for variable length arrays
ANTS/Examples/ImageMath.cxx:9382:37: error: variable length arrays are a
C99 feature, accepted as an extension [-Wvla]
   typename ImageType::Pointer images[argc-4];
                                      ^

Simply converting to std::vector resolved the compilation issue.

git-svn-id: https://advants.svn.sourceforge.net/svnroot/advants/trunk@1404 fd2da0a4-d968-48df-9cb5-d8c496287cbf